#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import requests
import json
from datetime import datetime, timedelta

webhook_url = 'https://open.feishu.cn/open-apis/bot/v2/hook/84da8bbf-9ccf-4179-b8da-1f0e9739f9ae'

yesterday_cn = (datetime.now() - timedelta(days=1)).strftime('%Y年%m月%d日')
date_str = (datetime.now() - timedelta(days=1)).strftime('%Y-%m-%d')

print("="*70)
print("Ocean AI Daily Report - Sending to Feishu")
print("="*70)

card = {
    "msg_type": "interactive",
    "card": {
        "header": {
            "title": {"tag": "plain_text", "content": f"Ocean AI Report - {yesterday_cn}"},
            "template": "blue"
        },
        "elements": [
            {
                "tag": "div",
                "text": {
                    "tag": "lark_md",
                    "content": "**Report Date** {}\n\n**Topics Covered**\nOcean AI | Digital Twin | Data Quality | Data Processing | Data Management | Open Cruises".format(date_str)
                }
            },
            {"tag": "hr"},
            {
                "tag": "div",
                "text": {
                    "tag": "lark_md",
                    "content": "**Reports Statistics**\nTotal Articles: 31\nHTML Report: daily_reports/Report_{}.html\nFeishu Doc: Check feishu_doc_url.txt\nExecution Log: .codebuddy/automations/ai/memory.md".format(date_str)
                }
            },
            {"tag": "hr"},
            {
                "tag": "note",
                "elements": [
                    {"tag": "plain_text", "content": "Generated by WorkBuddy Ocean AI Report System"}
                ]
            }
        ]
    }
}

print("\n[Step 1] Sending card to Feishu webhook...")

try:
    resp = requests.post(webhook_url, json=card, timeout=10)
    result = resp.json()
    
    code = result.get('code')
    msg = result.get('msg')
    
    print(f"[Step 2] Server Response:")
    print(f"    Status Code: {resp.status_code}")
    print(f"    Return Code: {code}")
    print(f"    Return Message: {msg}")
    
    if code == 0:
        print(f"\n[SUCCESS] Report sent to Feishu successfully!")
        print(f"Check your Feishu group to view the message.")
    else:
        print(f"\n[FAILED] Sending failed")
        
except Exception as e:
    print(f"[ERROR] {e}")

print("\n" + "="*70)
